version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "1000:100"
    network_mode: 'host'

    volumes:
      - /opt/appdata/jellyfin:/config
      - /opt/appdata/jellyfin-cache:/cache
      - /srv/dev-disk-by-label-nas2020/media:/media
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    #environment:
    #  - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"