version: '3.5'
services:
  syncthing-colanah:
    image: syncthing/syncthing
    network_mode: "host"
    hostname: syncthing-colanah
    volumes:
      - /srv/dev-disk-by-label-nas2020/datarrhea/home/colanah:/var/syncthing
      - /opt/appdata/syncthing:/var/syncthing/config
    environment:
      - PUID=1001
      - PGID=100
    #ports:
    #  - 8384:8384 # Web UI
    #  - 22000:22000/tcp # TCP file transfers
    #  - 22000:22000/udp # QUIC file transfers
    #  - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped