version: "2.1"
services:
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=100
      - CLI_ARGS=--log-file=/config/logs.log --log-level=Debug
    volumes:
      - /opt/appdata/duplicati:/config
      - /opt/backups:/backups
      - /srv/01e6ac58-fb44-48c7-a5da-33723c61436b:/source
      - /srv/dev-disk-by-id-ata-ST31500341AS_9VS2VX7N-part1/osbackup:/source/osbackup
    ports:
      - 8200:8200
    restart: unless-stopped